def output_rds(uploadurl,db_name,db_region):

    print("/////////////////////////// Your Infrastructure ///////////////////////////////")
    print("///")
    print("/// ________________________________________________________________________")
    print("/// |                                                                      |")
    print("/// |  [S3-Bucket]                                                         |")
    print("/// |     ______________________[Internet-Gateway]__________________       |")
    print("/// |    |                                    |                     |      |")
    print("/// |    |                                    |                     |      |")
    print("/// |    |   _____Pub-VPC____          _______|_________            |      |")
    print("/// |    |  | Subnet 1 / EC2 |        |   Route-Table   |           |      |")
    print("/// |    |  |________________|________|_________________|           |      |")
    print("/// |    |  |    Subnet 2    |______                                |      |")
    print("/// |    |  |________________|      |          _____Priv-VPC_____   |      |")
    print("/// |    |  |    Subnet 3    |      |__________|  Subnet 1 /SQL  |  |      |")
    print("/// |    |  |________________|                 |_________________|  |      |")
    print("/// |    |                                     |     Subnet 2    |  |      |")
    print("/// |    |                                     |_________________|  |      |")
    print("/// |    |                                     |     Subnet 3    |  |      |")
    print("/// |    |                                     |_________________|  |      |")
    print("/// |    |__________________________________________________________|      |")
    print("/// |                                                                      |")
    print("/// |______________________________________________________________________|")   
    print("/// Please use this command in your terminal: " + uploadurl+ "")
    print("/// Your SQL-DB is callable at following Endpoint: "+ db_name +".cpbioztdqjbb."+db_region+ "rds.amazonaws.com")
